export const elements = {
  appShell: document.querySelector("#appShell"),
  newNoteButton: document.querySelector("#newNoteButton"),
  searchInput: document.querySelector("#searchInput"),
  noteCount: document.querySelector("#noteCount"),
  saveStatus: document.querySelector("#saveStatus"),
  noteList: document.querySelector("#noteList"),
  currentDate: document.querySelector("#currentDate"),
  wordCount: document.querySelector("#wordCount"),
  lineCount: document.querySelector("#lineCount"),
  readTime: document.querySelector("#readTime"),
  imageCount: document.querySelector("#imageCount"),
  checklistStatus: document.querySelector("#checklistStatus"),
  focusButton: document.querySelector("#focusButton"),
  pinButton: document.querySelector("#pinButton"),
  downloadButton: document.querySelector("#downloadButton"),
  deleteButton: document.querySelector("#deleteButton"),
  imageLayoutSelect: document.querySelector("#imageLayoutSelect"),
  imageStyleSelect: document.querySelector("#imageStyleSelect"),
  addImageButton: document.querySelector("#addImageButton"),
  imageInput: document.querySelector("#imageInput"),
  templateSelect: document.querySelector("#templateSelect"),
  titleInput: document.querySelector("#titleInput"),
  tagInput: document.querySelector("#tagInput"),
  imageBoard: document.querySelector("#imageBoard"),
  contentInput: document.querySelector("#contentInput"),
  template: document.querySelector("#noteItemTemplate")
};
